name: Auto Post Result Bharat

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
      - name: Install Python Dependencies
        run: |
          pip install requests bs4 Pillow pdf2image
      - name: Run Scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
